Sc0up/scoup-backend

- .github/ISSUE_TEMPLATE/template-for-writing-acceptance-criteria.md
저희 시트에 있는 대상 항목을 적을 수 있는 칸을 넣어보는건 어떤가요?
굳이 칸을 안 만들고
given에 같이 넣어주거나, 별도로 표기하는 방식도 있을 것 같아요
> 인수 조건 작성용 이슈 템플릿에 target 추가

- src/main/java/com/postsquad/scoup/web/common/ErrorResponse.java
- src/main/java/com/postsquad/scoup/web/error/controller/ErrorControllerAdvice.java
- src/main/java/com/postsquad/scoup/web/error/controller/response/ErrorResponse.java
요구사항 번호가 없어서 일단 임의로 브랜치명을 지정했습니다.
의견 부탁드립니다!
> [Freddie] ErrorResponse 추가

- src/main/java/com/postsquad/scoup/web/user/controller/UserController.java
- src/main/java/com/postsquad/scoup/web/user/controller/request/SignUpRequest.java
- src/main/java/com/postsquad/scoup/web/user/domain/User.java
- src/main/java/com/postsquad/scoup/web/user/domain/UserFactory.java
- src/main/java/com/postsquad/scoup/web/user/repository/UserRepository.java
- src/main/java/com/postsquad/scoup/web/user/service/UserService.java
- src/test/java/com/postsquad/scoup/web/user/controller/UserAcceptanceTest.java
- src/test/java/com/postsquad/scoup/web/user/domain/UserFactoryTest.java
- src/test/java/com/postsquad/scoup/web/user/repository/UserRepositoryTest.java
이메일 회원가입 완료했습니다.
- 회원가입
- 기본적인 validation 체크
> [Freddie] 이메일 회원가입

- src/main/java/com/postsquad/scoup/ScoupApplication.java
- src/main/java/com/postsquad/scoup/web/BaseEntity.java
- src/main/java/com/postsquad/scoup/web/common/BaseEntity.java
생성 시간 및 수정 시간을 자동화하기 위해 JpaAuditing을 적용한 BaseEntity 클래스를 추가하였습니다.
> [Jane] BaseEntity 클래스 추가

- src/main/java/com/postsquad/scoup/web/user/domain/User.java
- src/test/java/com/postsquad/scoup/web/user/controller/UserAcceptanceTest.java
> [Freddie] UserAcceptanceTest에 BaseEntity 적용

- src/test/java/com/postsquad/scoup/web/user/controller/UserAcceptanceTest.java
사용자 기본 로케일에 따라 테스트 결과가 달라지는 것을 확인
일단 User인수테스트에만 넣었습니다..
관련 논의는 #30 에서 마저 하는게 좋을 것 같네요
@janeljs 새리의 테스트 동작이 작동아예 되지 않아 작동확인만 되면 바로 머지하겠습니다.
> User 인수 테스트 Validation 검증 헤더에 로케일 설정

- .gitignore
MapStruct같이 소스 자동 생성해주는 경우 /src/main/generated가 기본 폴더로 지정돼있습니다.
따라서 해당 폴더 지정해뒀습니다.
> [Freddie] .gitignore에 generated 추가

- src/main/java/com/postsquad/scoup/web/error/controller/ErrorControllerAdvice.java
- src/main/java/com/postsquad/scoup/web/error/controller/response/ErrorResponse.java
- src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
MethodArgumentNotValidException의 getMessage는 사용하기가 애매해서 임의의 메세지를 넣어줬습니다.
의견 부탁드려요
> [Freddie] ErrorControllerAdvice에서 메세지를 좀 더 구체적으로 반환하도록 수정

- src/main/java/com/postsquad/scoup/web/error/controller/ErrorControllerAdvice.java
- src/main/java/com/postsquad/scoup/web/error/controller/response/ErrorResponse.java
- src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
Method argument not valid. 로 업데이트 되지 않은 부분이 있어 수정했습니다.
수정하며 추가로 #28 에서 합쳐졌던 부분에 message 추가해줬습니다.
에러 수정을 위해 바로 머지하겠습니다.
> [Freddie] Error response message 반영 및 테스트 케이스 수정

- src/main/java/com/postsquad/scoup/web/auth/GitHubOAuth.java
- src/main/java/com/postsquad/scoup/web/auth/controller/OAuthController.java
- src/main/java/com/postsquad/scoup/web/auth/request/AccessTokenRequest.java
- src/main/java/com/postsquad/scoup/web/auth/service/OAuthService.java
- src/main/java/com/postsquad/scoup/web/config/JasyptConfig.java
- src/main/java/com/postsquad/scoup/web/config/WebConfig.java
- src/main/java/com/postsquad/scoup/web/error/controller/response/ErrorResponse.java
- src/main/java/com/postsquad/scoup/web/group/controller/response/GroupValidationResponse.java
- src/main/java/com/postsquad/scoup/web/user/controller/UserController.java
- src/main/java/com/postsquad/scoup/web/user/controller/request/SignUpRequest.java
- src/main/java/com/postsquad/scoup/web/user/controller/response/EmailValidationResponse.java
- src/main/java/com/postsquad/scoup/web/user/controller/response/SocialAuthenticationResponse.java
- src/main/java/com/postsquad/scoup/web/user/domain/User.java
- src/main/java/com/postsquad/scoup/web/user/service/UserService.java
- src/main/resources/application.properties
- src/test/java/com/postsquad/scoup/web/AcceptanceTestBase.java
- src/test/java/com/postsquad/scoup/web/auth/OAuthAcceptanceTest.java
- src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
- src/test/java/com/postsquad/scoup/web/user/mapper/UserMapperTest.java
- src/test/java/com/postsquad/scoup/web/user/repository/UserRepositoryTest.java
- src/test/java/com/postsquad/scoup/web/user/service/UserServiceTest.java
이상한거나 마음에 안 드는 부분 있으면 말씀 부탁드려요!
> [Freddie] indentation 수정

- src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
Reverts Sc0up/scoup-backend#64
테스트 실패
-깃헙 액션 활성화 되지 않음
> Revert "[Freddie] 깃헙액션 테스트 위해 테스트 실패하도록 변경"

- src/main/java/com/postsquad/scoup/web/user/controller/UserController.java
- src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
- /sign-up -> /users 로 변경
- /validate/* -> /users/validate/* 로 변경
> [Freddie] User api에 users 추가

- src/main/java/com/postsquad/scoup/web/user/controller/UserController.java
- src/main/java/com/postsquad/scoup/web/user/controller/response/NicknameValidationResponse.java
- src/main/java/com/postsquad/scoup/web/user/repository/UserRepository.java
- src/main/java/com/postsquad/scoup/web/user/service/UserService.java
- src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
닉네임 중복확인 구현 완료하였습니다. 전체적인 로직은 이메일 중복확인과 같습니다.
감사합니다!
> [새리][1-3-2] 닉네임 중복확인

- src/main/java/com/postsquad/scoup/web/user/repository/UserRepository.java
- src/main/java/com/postsquad/scoup/web/user/service/NicknameAlreadyExistsException.java
- src/main/java/com/postsquad/scoup/web/user/service/UserAlreadyExistsException.java
- src/main/java/com/postsquad/scoup/web/user/service/UserService.java
- src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
요구사항이 복잡하지 않아서 기능적으로 큰 변화는 없었습니다.
리팩토링할 부분들이 좀 보여서 주석으로 메모해놨는데 머지 이후에 새로운 pr로 리팩토링 작업하겠습니다.
> [Freddie][1-2-3] 회원가입 시 닉네임 이미 존재하면 회원가입 실패

- src/main/java/com/postsquad/scoup/web/user/repository/UserRepository.java
- src/main/java/com/postsquad/scoup/web/user/service/EmailAlreadyExistsException.java
- src/main/java/com/postsquad/scoup/web/user/service/UserAlreadyExistsException.java
- src/main/java/com/postsquad/scoup/web/user/service/UserService.java
- src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
- src/test/java/com/postsquad/scoup/web/user/service/UserServiceTest.java
예외 처리 로직과 테스트 소폭 개선 및 관련 테스트 추가했습니다.
> [Freddie] 이메일로 회원가입 리팩토링

- src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
- src/test/java/com/postsquad/scoup/web/user/provider/EmailSignUpProvider.java
- src/test/java/com/postsquad/scoup/web/user/provider/SignUpWhenUserAlreadyExistsProvider.java
- src/test/java/com/postsquad/scoup/web/user/provider/SignUpWithValidationProvider.java
- src/test/java/com/postsquad/scoup/web/user/provider/SocialSignUpProvider.java
- src/test/java/com/postsquad/scoup/web/user/provider/ValidateEmailProvider.java
- src/test/java/com/postsquad/scoup/web/user/provider/ValidateEmailRequestParamProvider.java
- src/test/java/com/postsquad/scoup/web/user/provider/ValidateNicknameProvider.java
- src/test/java/com/postsquad/scoup/web/user/provider/ValidateNicknameRequestParamProvider.java
테스트의 리소스를 제공하는 provider가 많아져 가독성을 위해 provider 메서드들을 테스트 클래스에서 분리했습니다.
Closes #119
> [Jane] UserAcceptanceTest 클래스에서 provider 분리

- src/main/resources/auth.properties
https://scoup-323503.firebaseapp.com/__/auth/handler에서
http://localhost:3000/api/auth/social/google로 redirect uri를 수정했습니다.
✅ Closes: #126
> [Jane] Google OAuth Redirect URI 수정

- src/main/java/com/postsquad/scoup/web/schedule/controller/response/ConfirmedParticipantResponse.java
- src/main/java/com/postsquad/scoup/web/schedule/controller/response/ConfirmedScheduleResponse.java
- src/main/java/com/postsquad/scoup/web/schedule/controller/response/ConfirmedScheduleResponses.java
- src/main/java/com/postsquad/scoup/web/schedule/controller/response/ScheduleCandidateResponse.java
- src/main/java/com/postsquad/scoup/web/schedule/controller/response/ScheduleCandidateResponses.java
- src/main/java/com/postsquad/scoup/web/schedule/controller/response/UnconfirmedScheduleResponse.java
- src/main/java/com/postsquad/scoup/web/schedule/controller/response/UnconfirmedScheduleResponses.java
확정 일정 및 미확정 일정 조회를 위한 DTO를 추가했습니다.
> [Jane][4-1-1] 확정 일정 및 미확정 일정 조회를 위한 DTO 추가

- build.gradle
- src/main/java/com/postsquad/scoup/ScoupApplication.java
- src/main/java/com/postsquad/scoup/web/config/WebConfig.java
오늘 저녁에 있을 전체 회의를 위해 Spring Rest Docs 적용 전 임시로 Swagger를 적용해보았습니다!
Closes #186
> Swagger 적용

- src/main/java/com/postsquad/scoup/web/config/WebConfig.java
CORS 설정을 추가했습니다.
✅ Closes: #198
> [Jane] CORS 설정 추가

- src/main/java/com/postsquad/scoup/web/group/controller/GroupController.java
- src/test/java/com/postsquad/scoup/web/group/GroupAcceptanceTest.java
204 No Content로 status 변경했습니다.
따라서 핸들러 리턴타입 void로 변경되었습니다.
테스트에서는 given을 이용하여 조회가능하도록 했습니다.
추가로 테스트의 given path표기에 pathParameter가 들어있지않아 함께 수정해줬습니다.
> [Freddie] 그룹 수정 200 -> 204로 변경

- src/main/java/com/postsquad/scoup/web/schedule/repository/ConfirmedScheduleRepository.java
- src/main/java/com/postsquad/scoup/web/schedule/service/ConfirmedScheduleService.java
- src/test/java/com/postsquad/scoup/web/schedule/ConfirmedScheduleAcceptanceTest.java
- src/test/java/com/postsquad/scoup/web/schedule/provider/ConfirmedScheduleReadAllProvider.java
- src/test/java/com/postsquad/scoup/web/schedule/repository/ConfirmedScheduleRepositoryTest.java
https://github.com/Sc0up/scoup-backend/pull/180#discussion_r726974298 리뷰에 따라 `@Query` 어노테이션을 사용하여 직접 쿼리를 작성하였고, n+1 문제 해결을 위해 fetch join을 사용하였습니다.
✅ Closes: #192
> [Jane][4-1-3] 그룹 아이디로 확정 일정 조회

- src/main/java/com/postsquad/scoup/web/auth/exception/OAuthException.java
- src/main/java/com/postsquad/scoup/web/auth/exception/OAuthRequestNotValidException.java
- src/main/java/com/postsquad/scoup/web/auth/exception/OAuthUserNotFoundException.java
- src/main/java/com/postsquad/scoup/web/auth/exception/TokenNotFoundException.java
- src/test/java/com/postsquad/scoup/web/auth/OAuthAcceptanceTest.java
- src/test/java/com/postsquad/scoup/web/group/GroupAcceptanceTest.java
예외 메세지와 Display 어노테이션의 마침표 제거했습니다.
혹시 이외 부분에 보이면 말씀 부탁드려요
> [Freddie] 마침표 제거

- src/main/java/com/postsquad/scoup/web/auth/controller/response/KakaoUserResponse.java
- src/main/java/com/postsquad/scoup/web/auth/mapper/SocialAuthenticationResponseMapper.java
- src/main/java/com/postsquad/scoup/web/auth/service/GitHubOAuth.java
- src/main/java/com/postsquad/scoup/web/auth/service/GoogleOAuth.java
- src/main/java/com/postsquad/scoup/web/auth/service/KakaoOAuth.java
- src/main/java/com/postsquad/scoup/web/signin/mapper/SignInResponseMapper.java
- src/main/java/com/postsquad/scoup/web/signin/service/SignInService.java
- src/main/java/com/postsquad/scoup/web/user/mapper/UserMapper.java
- 매퍼 메소드들 이름을 map으로 바꿨습니다.
- 패키지가 map 아닌 인터페이스를 옮겨줬습니다.
> [Freddie] Mapper 메소드 수정

- src/main/java/com/postsquad/scoup/ScoupApplication.java
- src/main/java/com/postsquad/scoup/web/config/SwaggerConfig.java
- src/main/java/com/postsquad/scoup/web/config/WebConfig.java
Swagger와 관련된 설정들을 모아줬습니다.
우선 WebConfig를 조금씩 정리해나가고 싶었습니다.
추가적으로 추후 스웨거를 제거해야하거나 특정 프로필에서만 실행시키고 싶을 경우 도움이 될 것 같습니다.
@janeljs 혹시 빠뜨린 부분 있으면 알려주세요!!
> [Freddie] SwaggerConfig 생성 후 관련 설정 이동

- src/main/java/com/postsquad/scoup/web/group/service/GroupService.java
- src/main/java/com/postsquad/scoup/web/schedule/controller/SchedulePollController.java
- src/main/java/com/postsquad/scoup/web/schedule/domain/ScheduleCandidate.java
- src/main/java/com/postsquad/scoup/web/schedule/exception/ScheduleCandidateNotFoundException.java
- src/main/java/com/postsquad/scoup/web/schedule/service/SchedulePollService.java
- src/main/java/com/postsquad/scoup/web/user/domain/User.java
- src/test/java/com/postsquad/scoup/web/schedule/SchedulePollAcceptanceTest.java
- Set으로 저장하도록 하여 같은 사용자가 중복투표하지 않도록 함
- Set에서 User Id로 판단하도록 User에 equals, hashcode 추가
> [4-8-1][Freddie]스케줄 투표 추가
